### ISSUE TITLE
Upgrade devtoolset

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-deploy#18]
https://github.com/GUDHI/gudhi-deploy/blob/39b97d66174015b99ca170a5f1401b8301a1405b/Dockerfile_for_pip#L9

8 is pretty old, and I think it is the reason why our official pip package is affected by https://github.com/GUDHI/gudhi-devel/issues/818 .

**Comment by VincentRouvreau** [comment]
Closed by #24
